<?php

namespace Tests\Feature\Api;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class StatusesTest extends TestCase
{
    protected $statusData, $statusErrorData;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->statusData = [
            "user_id" => 1,
            "day_id" => 1,
            "complety_time" => 120,
            "date" => "01-01-2023",
            "status" => "workDay",
            "hour_start" => "07:00",
            //"hour_end" => null,
        ];

        $this->statusErrorData = [
            "user_id" => "test",
            "day_id" => "test",
            "complety_time" => "test",
            "date" => "1-1-2023",
            "status" => "test",
            "hour_start" => "7:00",
            "hour_end" => "23",
        ];
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testApiCreateStatus()
    {
        $response = $this->post(route('status.store'), $this->statusData);

        $this->assertDatabaseHas('statuses', $this->statusData);
        $response->assertStatus(200);
    }

    public function testValidatedValues()
    {
        $response = $this->post(route('status.store'), $this->statusErrorData);

        $response->assertSessionHasErrors([
            "user_id",
            "day_id",
            "complety_time",
            "date",
            "status",
            "hour_start",
            "hour_end"
        ])->assertStatus(302);
    }

}
