<?php

namespace Tests\Feature\Api;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class StatusesTest extends TestCase
{
    protected $statusData, $statusErrorData, $statusMultiData, $statusSearchSingle, $statusSearchMulti;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->statusData = [
            "user_id" => 1,
            "day_id" => 1,
            "date_start" => "01-01-2023",
            "date_end" => "01-01-2023",
            "status" => "workDay",
            "hour_start" => "07:00",
            "hour_end" => "09:00",
        ];

        $this->statusMultiData = [
            "user_id" => 1,
            "day_id" => 1,
            "date_start" => "01-01-2023",
            "date_end" => "05-01-2023",
            "status" => "workDay",
            "hour_start" => "07:00",
            "hour_end" => "09:00",
        ];

        $this->statusErrorData = [
            "user_id" => "test",
            "day_id" => "test",
            "date_start" => "1-1-2023",
            "date_end" => "1-1-2023",
            "status" => "test",
            "hour_start" => "7:00",
            "hour_end" => "2:03",
        ];

        $this->statusSearchSingle = [
            "user_id" => 1,
            "day_id" => 1,
            "complety_time" => 120,
            "date" => "01-01-2023",
            "status" => "workDay",
            "hour_start" => "07:00",
            "hour_end" => "09:00",
        ];

        $this->statusSearchMulti = [
            [
                "user_id" => 1,
                "day_id" => 1,
                "complety_time" => 120,
                "date" => "01-01-2023",
                "status" => "workDay",
                "hour_start" => "07:00",
                "hour_end" => "09:00",
            ], [
                "user_id" => 1,
                "day_id" => 1,
                "complety_time" => 120,
                "date" => "03-01-2023",
                "status" => "workDay",
                "hour_start" => "07:00",
                "hour_end" => "09:00",
            ], [
                "user_id" => 1,
                "day_id" => 1,
                "complety_time" => 120,
                "date" => "05-01-2023",
                "status" => "workDay",
                "hour_start" => "07:00",
                "hour_end" => "09:00",
            ]
        ];
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testApiCreateSingleStatus()
    {
        $response = $this->post(route('status.store'), $this->statusData);

        $this->assertDatabaseHas('statuses', $this->statusSearchSingle);
        $response->assertStatus(200);
    }

    public function testApiCreateMultiStatus()
    {
        $response = $this->post(route('status.store'), $this->statusMultiData);

        $this->assertDatabaseHas('statuses', $this->statusSearchMulti[0])
            ->assertDatabaseHas('statuses', $this->statusSearchMulti[1])
            ->assertDatabaseHas('statuses', $this->statusSearchMulti[2]);
        $response->assertStatus(200);
    }

    public function testValidatedValues()
    {
        $response = $this->post(route('status.store'), $this->statusErrorData);

        $response->assertSessionHasErrors([
            "user_id",
            "day_id",
            "date_start",
            "date_end",
            "status",
            "hour_start",
            "hour_end"
        ])->assertStatus(302);
    }

}
